spring:
  aop:
    proxy-target-class: true
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true

# 所有环境通用的配置，放在这里
mybatis:
  # 实体类的存放路径
  type-aliases-package: com.zlsoft.pj.wx.api.domain
  mapper-locations: classpath:mapper/*.xml


pj:
  app:
    id: 1234
    secret: miyao
logging:
  level.com.zlsoft.pj.wx.api.mapper: debug